#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum tap_dance_codes {
  DANCE_0,
};



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        [0] = LAYOUT_split_3x5_3(
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
           KC_Q,            KC_W,           KC_E,           KC_R,       KC_T,                                                KC_Y,       KC_U,           KC_I,           KC_O,            KC_P,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
   LGUI_T(KC_A),    LSFT_T(KC_S),   LCTL_T(KC_D),   LALT_T(KC_F),       KC_G,                                                KC_H,LALT_T(KC_J),  LCTL_T(KC_K),   LSFT_T(KC_L),   LGUI_T(KC_QUOT),
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
           KC_Z,            KC_X,           KC_C,           KC_V,       KC_B,                                                KC_N,       KC_M,        KC_COMM,         KC_DOT,         KC_SLSH,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
                                                LT(5,KC_ESC),   LT(1,KC_SPC),   LT(2,KC_BSPC),          LT(3,KC_TAB), LT(4,KC_ENT), KC_DEL),
                                             //|-------------+----------------+---------------|        |------------+-----------+-----------|

        [1] = LAYOUT_split_3x5_3(
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
          KC_NO,           KC_NO,          KC_NO,          KC_NO,      KC_NO,                                               KC_NO,    C(KC_C),        C(KC_V),          KC_NO,           KC_NO,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
        KC_LGUI,         KC_LSFT,        KC_LCTL,        KC_LALT,      KC_NO,                                             CW_TOGG,    KC_PGUP,        KC_PGDN,        KC_HOME,          KC_END,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
          KC_NO,           KC_NO,          KC_NO,          KC_NO,      KC_NO,                                         TD(DANCE_0),    KC_LEFT,        KC_RGHT,          KC_UP,         KC_DOWN,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
                                                      KC_TRNS,         KC_TRNS,         KC_NO,                KC_TAB,     KC_ENT,    KC_DEL),
                                             //|-------------+----------------+---------------|        |------------+-----------+-----------|

        [2] = LAYOUT_split_3x5_3(
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
          KC_NO,           KC_NO,          KC_NO,          KC_NO,      KC_NO,                                             KC_MINS,    KC_LBRC,        KC_RBRC,          KC_NO,           KC_NO,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
        KC_TRNS,         KC_TRNS,        KC_TRNS,        KC_TRNS,      KC_NO,                                             KC_SCLN,    KC_BSLS,          KC_NO,          KC_NO,           KC_NO,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
          KC_NO,           KC_NO,          KC_NO,          KC_NO,      KC_NO,                                              KC_GRV,      KC_NO,          KC_NO,          KC_NO,           KC_NO,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
                                                      KC_TRNS,           KC_NO,       KC_TRNS,                KC_TAB,     KC_ENT,     KC_NO),
                                             //|-------------+----------------+---------------|        |------------+-----------+-----------|

        [3] = LAYOUT_split_3x5_3(
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
          KC_NO,           KC_NO,          KC_NO,          KC_NO,      KC_NO,                                                KC_7,       KC_8,           KC_9,        KC_MINS,          KC_EQL,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
        KC_TRNS,         KC_TRNS,        KC_TRNS,        KC_TRNS,      KC_NO,                                                KC_4,       KC_5,           KC_6,          KC_NO,          KC_INS,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
         KC_NO,            KC_NO,          KC_NO,          KC_NO,      KC_NO,                                                KC_1,       KC_2,           KC_3,         KC_DOT,          KC_GRV,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
                                                        KC_NO,          KC_SPC,        KC_BSPC,              KC_TRNS,      KC_NO,      KC_0),
                                             //|-------------+----------------+---------------|        |------------+-----------+-----------|


        [4] = LAYOUT_split_3x5_3(
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
          KC_NO,           KC_NO,          KC_NO,        RGB_TOG,    QK_BOOT,                                               KC_F7,      KC_F8,          KC_F9,        RGB_TOG,          KC_F12,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
        KC_TRNS,         KC_TRNS,        KC_TRNS,        KC_TRNS,      KC_NO,                                               KC_F4,      KC_F5,          KC_F6,          KC_NO,          KC_F11,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
          KC_NO,           KC_NO,          KC_NO,          KC_NO,      KC_NO,                                               KC_F1,      KC_F2,          KC_F3,          KC_NO,           KC_NO,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
                                                      KC_TRNS,          KC_SPC,        KC_BSPC,                KC_NO,    KC_TRNS,    KC_F10),
                                             //|-------------+----------------+---------------|        |------------+-----------+-----------|


        [5] = LAYOUT_split_3x5_3(
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
          KC_NO,           KC_NO,          KC_NO,          KC_NO,      KC_NO,                                               KC_NO,    KC_WH_U,        KC_MS_U,        KC_WH_D,           KC_NO,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
        KC_TRNS,         KC_TRNS,        KC_TRNS,        KC_TRNS,      KC_NO,                                               KC_NO,    KC_MS_L,        KC_MS_D,        KC_MS_R,           KC_NO,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
          KC_NO,           KC_NO,          KC_NO,          KC_NO,      KC_NO,                                               KC_NO,      KC_NO,          KC_NO,          KC_NO,           KC_NO,
//|------------+----------------+---------------+---------------+-----------|                                       |------------+-----------+---------------+---------------+----------------|
                                                      KC_TRNS,           KC_NO,          KC_NO,              KC_BTN1,    KC_BTN2,      KC_NO)
                                             //|-------------+----------------+---------------|        |------------+-----------+-----------|

};

// manually added by jcarson
void keyboard_post_init_user(void) {
    rgb_matrix_enable_noeeprom();
    rgb_matrix_mode(1); // solid color
    rgb_matrix_sethsv_noeeprom(HSV_WHITE);
}

// layer_state_t layer_state_set_user(layer_state_t state){
//     // xprintf("Layer State: 0b%032lb (%u)\n", state, get_highest_layer(state));
//     return state;
// }

bool rgb_matrix_indicators_user(void) {
    uint8_t left_win = 16;
    uint8_t left_shift = 13;
    // uint8_t left_ctrl = 10;
    // uint8_t left_alt = 6;
    // uint8_t right_win = 16;
    // uint8_t right_shift = 16;
    // uint8_t right_ctrl = 16;
    // uint8_t right_alt = 16;

    switch (get_highest_layer(layer_state)) {
        
        case 5:
            rgb_matrix_set_color_all(0,0,0);
            HSV hsv_purple = {HSV_PURPLE};
            hsv_purple.v   = rgb_matrix_config.hsv.v;
            RGB rgb_purple = hsv_to_rgb(hsv_purple);
            HSV hsv_orange = {HSV_ORANGE};
            hsv_orange.v   = rgb_matrix_config.hsv.v;
            RGB rgb_orange = hsv_to_rgb(hsv_orange);
            // mod keys LHS/
            rgb_matrix_set_color(left_win, rgb_purple.r, rgb_purple.g, rgb_purple.b);
            rgb_matrix_set_color(left_shift, rgb_purple.r, rgb_purple.g, rgb_purple.b);
            rgb_matrix_set_color(19, rgb_purple.r, rgb_purple.g, rgb_purple.b);
            rgb_matrix_set_color(22, rgb_purple.r, rgb_purple.g, rgb_purple.b);

            rgb_matrix_set_color(37, rgb_orange.r, rgb_orange.g, rgb_orange.b);
            rgb_matrix_set_color(38, rgb_purple.r, rgb_purple.g, rgb_purple.b);
            rgb_matrix_set_color(43, rgb_purple.r, rgb_purple.g, rgb_purple.b);
            rgb_matrix_set_color(44, rgb_purple.r, rgb_purple.g, rgb_purple.b); 
            rgb_matrix_set_color(45, rgb_orange.r, rgb_orange.g, rgb_orange.b);
            rgb_matrix_set_color(46, rgb_purple.r, rgb_purple.g, rgb_purple.b);
            break;
        case 4:
            rgb_matrix_set_color_all(0,0,0);
            HSV hsv_red = {HSV_RED};
            hsv_red.v   = rgb_matrix_config.hsv.v;
            RGB rgb_red = hsv_to_rgb(hsv_red);
            HSV hsv_gold = {HSV_GOLD};
            hsv_gold.v   = rgb_matrix_config.hsv.v;
            RGB rgb_gold = hsv_to_rgb(hsv_gold);
            // mod keys LHS/
            rgb_matrix_set_color(9, rgb_gold.r, rgb_gold.g, rgb_gold.b);
            rgb_matrix_set_color(10, rgb_gold.r, rgb_gold.g, rgb_gold.b);
            rgb_matrix_set_color(left_win, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(left_shift, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(19, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(22, rgb_red.r, rgb_red.g, rgb_red.b);

            rgb_matrix_set_color(34, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(35, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(36, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(37, rgb_red.r, rgb_red.g, rgb_red.b); 
            rgb_matrix_set_color(38, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(39, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(41, rgb_red.r, rgb_red.g, rgb_red.b); 
            rgb_matrix_set_color(42, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(43, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(44, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(49, rgb_red.r, rgb_red.g, rgb_red.b);
            rgb_matrix_set_color(50, rgb_red.r, rgb_red.g, rgb_red.b);
            break;
        case 3:
            rgb_matrix_set_color_all(0,0,0);
            HSV hsv_turquoise = {HSV_TURQUOISE};
            hsv_turquoise.v   = rgb_matrix_config.hsv.v;
            RGB rgb_turquoise = hsv_to_rgb(hsv_turquoise);
            // mod keys LHS/
            rgb_matrix_set_color(left_win, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(left_shift, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(19, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(22, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);

            rgb_matrix_set_color(34, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(35, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(36, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(37, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b); 
            rgb_matrix_set_color(38, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(39, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(41, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b); 
            rgb_matrix_set_color(42, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(43, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            rgb_matrix_set_color(44, rgb_turquoise.r, rgb_turquoise.g, rgb_turquoise.b);
            break;
        case 2:
            rgb_matrix_set_color_all(0,0,0);
            HSV hsv_yellow = {HSV_YELLOW};
            hsv_yellow.v   = rgb_matrix_config.hsv.v;
            RGB rgb_yellow = hsv_to_rgb(hsv_yellow);
            // mod keys LHS/
            rgb_matrix_set_color(left_win, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b);
            rgb_matrix_set_color(left_shift, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b);
            rgb_matrix_set_color(19, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b);
            rgb_matrix_set_color(22, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b);

            rgb_matrix_set_color(34, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b);
            rgb_matrix_set_color(35, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b);
            rgb_matrix_set_color(36, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b);
            rgb_matrix_set_color(37, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b); 
            rgb_matrix_set_color(38, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b);
            rgb_matrix_set_color(44, rgb_yellow.r, rgb_yellow.g, rgb_yellow.b);          
            break;
        case 1:
            HSV hsv_green = {HSV_GREEN};
            hsv_green.v   = rgb_matrix_config.hsv.v;
            RGB rgb_green = hsv_to_rgb(hsv_green);
            HSV hsv_springgreen = {HSV_SPRINGGREEN};
            hsv_springgreen.v   = rgb_matrix_config.hsv.v;
            RGB rgb_springgreen = hsv_to_rgb(hsv_springgreen);
            rgb_matrix_set_color_all(0, 0, 0);
            rgb_matrix_set_color(left_win, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(left_shift, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(19, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(22, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(34, rgb_green.r, rgb_green.g, rgb_green.b);
            rgb_matrix_set_color(35, rgb_green.r, rgb_green.g, rgb_green.b);
            rgb_matrix_set_color(37, rgb_green.r, rgb_green.g, rgb_green.b);
            rgb_matrix_set_color(44, rgb_green.r, rgb_green.g, rgb_green.b);
            // these keys are used more so I brightened them
            rgb_matrix_set_color(38, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(39, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(42, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(43, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(46, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(47, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(48, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            rgb_matrix_set_color(49, rgb_springgreen.r, rgb_springgreen.g*5, rgb_springgreen.b);
            break;
        case 0:
            HSV hsv_blue = {HSV_BLUE};
            hsv_blue.v   = rgb_matrix_config.hsv.v;
            RGB rgb_blue = hsv_to_rgb(hsv_blue);
            // underglow off
            rgb_matrix_set_color(0, 0, 0, 0);
            rgb_matrix_set_color(1, 0, 0, 0);
            rgb_matrix_set_color(2, 0, 0, 0);
            rgb_matrix_set_color(3, 0, 0, 0);
            rgb_matrix_set_color(4, 0, 0, 0);
            rgb_matrix_set_color(5, 0, 0, 0);
            rgb_matrix_set_color(32, 0, 0, 0);
            rgb_matrix_set_color(31, 0, 0, 0);
            rgb_matrix_set_color(30, 0, 0, 0);
            rgb_matrix_set_color(29, 0, 0, 0);
            rgb_matrix_set_color(28, 0, 0, 0);
            rgb_matrix_set_color(27, 0, 0, 0);
            rgb_matrix_set_color(26, 0, 0, 0);

            // mod keys LHS/
            rgb_matrix_set_color(left_win, rgb_blue.r, 0, rgb_blue.b);
            rgb_matrix_set_color(left_shift, rgb_blue.r, 0, rgb_blue.b);
            rgb_matrix_set_color(19, rgb_blue.r, 0, rgb_blue.b);
            rgb_matrix_set_color(22, rgb_blue.r, 0, rgb_blue.b);
            // mod keys RHS/
            rgb_matrix_set_color(38, rgb_blue.r, 0, rgb_blue.b);
            rgb_matrix_set_color(43, rgb_blue.r, 0, rgb_blue.b);
            rgb_matrix_set_color(46, rgb_blue.r, 0, rgb_blue.b);
            rgb_matrix_set_color(49, rgb_blue.r, 0, rgb_blue.b);
            // /mod keys
            break;
        default:
            break;
    }
    return false;
}

typedef struct {
    bool is_press_action;
    uint8_t step;
} tap;

enum {
    SINGLE_TAP = 1,
    SINGLE_HOLD,
    DOUBLE_TAP,
    DOUBLE_HOLD,
    DOUBLE_SINGLE_TAP,
    MORE_TAPS
};

/* Need to get this working::::

static tap dance_state[1];

uint8_t dance_step(tap_dance_state_t *state);

uint8_t dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}



void on_dance_0(tap_dance_state_t *state, void *user_data);
void dance_0_finished(tap_dance_state_t *state, void *user_data);
void dance_0_reset(tap_dance_state_t *state, void *user_data);

void on_dance_0(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(LCTL(KC_GRAVE));
        tap_code16(LCTL(KC_GRAVE));
        tap_code16(LCTL(KC_GRAVE));
    }
    if(state->count > 3) {
        tap_code16(LCTL(KC_GRAVE));
    }
}

void dance_0_finished(tap_dance_state_t *state, void *user_data) {
    dance_state[0].step = dance_step(state);
    switch (dance_state[0].step) {
        case SINGLE_TAP: register_code16(LCTL(KC_GRAVE)); break;
        case SINGLE_HOLD: register_code16(KC_MS_BTN1); break;
        case DOUBLE_TAP: register_code16(LCTL(KC_GRAVE)); register_code16(LCTL(KC_GRAVE)); break;
        case DOUBLE_SINGLE_TAP: tap_code16(LCTL(KC_GRAVE)); register_code16(LCTL(KC_GRAVE));
    }
}

void dance_0_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state[0].step) {
        case SINGLE_TAP: unregister_code16(LCTL(KC_GRAVE)); break;
        case SINGLE_HOLD: unregister_code16(KC_MS_BTN1); break;
        case DOUBLE_TAP: unregister_code16(LCTL(KC_GRAVE)); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(LCTL(KC_GRAVE)); break;
    }
    dance_state[0].step = 0;
}

tap_dance_action_t tap_dance_actions[] = {
        [DANCE_0] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_0, dance_0_finished, dance_0_reset),
};

*/
